
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  # name: your-registered-name
  version: '1.0.0RC3' # just for humans, typically '1.2+git' or '1.3.2'
  summary: more convenient one-time-pad encryption
  description: |
    TBA

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    ParaCrypt:
      source: https://github.com/gutow/ParaCrypt.git
      plugin: python
      python-version: python3
      python-packages: wxpython
  apps:
    ParaCrypt:
      command: wxParaCrypt.py
      icon: ParaCryptArt/ParaCryptIcon.svg
  
